USE [master]
GO
/****** Object:  Database [NHibernateTestDemo]    Script Date: 2016/3/23 16:43:38 ******/
CREATE DATABASE [NHibernateTestDemo]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'NHibernateTestDemo', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\NHibernateTestDemo.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'NHibernateTestDemo_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\NHibernateTestDemo_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [NHibernateTestDemo] SET COMPATIBILITY_LEVEL = 110
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [NHibernateTestDemo].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [NHibernateTestDemo] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [NHibernateTestDemo] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [NHibernateTestDemo] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [NHibernateTestDemo] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [NHibernateTestDemo] SET ARITHABORT OFF 
GO
ALTER DATABASE [NHibernateTestDemo] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [NHibernateTestDemo] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [NHibernateTestDemo] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [NHibernateTestDemo] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [NHibernateTestDemo] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [NHibernateTestDemo] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [NHibernateTestDemo] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [NHibernateTestDemo] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [NHibernateTestDemo] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [NHibernateTestDemo] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [NHibernateTestDemo] SET  DISABLE_BROKER 
GO
ALTER DATABASE [NHibernateTestDemo] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [NHibernateTestDemo] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [NHibernateTestDemo] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [NHibernateTestDemo] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [NHibernateTestDemo] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [NHibernateTestDemo] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [NHibernateTestDemo] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [NHibernateTestDemo] SET RECOVERY FULL 
GO
ALTER DATABASE [NHibernateTestDemo] SET  MULTI_USER 
GO
ALTER DATABASE [NHibernateTestDemo] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [NHibernateTestDemo] SET DB_CHAINING OFF 
GO
ALTER DATABASE [NHibernateTestDemo] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [NHibernateTestDemo] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
EXEC sys.sp_db_vardecimal_storage_format N'NHibernateTestDemo', N'ON'
GO
USE [NHibernateTestDemo]
GO
/****** Object:  Table [dbo].[Catalog]    Script Date: 2016/3/23 16:43:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Catalog](
	[Id] [nvarchar](64) NULL,
	[PersonId] [nvarchar](64) NULL
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Class]    Script Date: 2016/3/23 16:43:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Class](
	[Id] [nvarchar](64) NOT NULL,
	[Name] [nvarchar](64) NULL,
	[TeacherId] [nvarchar](64) NULL,
 CONSTRAINT [PK_Catalog] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Family]    Script Date: 2016/3/23 16:43:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Family](
	[Id] [nvarchar](64) NOT NULL,
	[Address] [nvarchar](64) NULL,
 CONSTRAINT [PK_Family] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Person]    Script Date: 2016/3/23 16:43:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Person](
	[Id] [nvarchar](64) NULL,
	[Name] [nvarchar](64) NULL
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Role]    Script Date: 2016/3/23 16:43:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Role](
	[Id] [nvarchar](64) NOT NULL,
	[Name] [nvarchar](64) NULL,
 CONSTRAINT [PK_Role] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Student]    Script Date: 2016/3/23 16:43:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Student](
	[Id] [nvarchar](64) NOT NULL,
	[Name] [nvarchar](64) NULL,
	[ClassId] [nvarchar](64) NULL,
 CONSTRAINT [PK_Name] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Teacher]    Script Date: 2016/3/23 16:43:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Teacher](
	[Id] [nvarchar](64) NOT NULL,
	[Name] [nvarchar](64) NULL,
 CONSTRAINT [PK_Teacher] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[UserRole]    Script Date: 2016/3/23 16:43:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UserRole](
	[UserId] [nvarchar](64) NULL,
	[RoleId] [nvarchar](64) NULL
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Users]    Script Date: 2016/3/23 16:43:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[Id] [nvarchar](64) NOT NULL,
	[Name] [nvarchar](64) NULL,
 CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING ON

GO
/****** Object:  Index [IX_Catalog]    Script Date: 2016/3/23 16:43:38 ******/
CREATE NONCLUSTERED INDEX [IX_Catalog] ON [dbo].[Class]
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Student]  WITH CHECK ADD  CONSTRAINT [FK_Student_Class] FOREIGN KEY([ClassId])
REFERENCES [dbo].[Class] ([Id])
GO
ALTER TABLE [dbo].[Student] CHECK CONSTRAINT [FK_Student_Class]
GO
USE [master]
GO
ALTER DATABASE [NHibernateTestDemo] SET  READ_WRITE 
GO
